### ISSUE TITLE
Compile latest branch in Visual Studio failing

### ISSUE THREAD

**Issue by boingball** [Scope-IT/marksman#11]
I'm trying to compile Marksman on Windows using Visual Studio 2017.

However it seems that the SnipeSharp API Reference doesn't seem to match the code.

The marksman code trying to call SearchFilter / Location / Statuslabel cannot as theirs no a constructor to take 1 argument. (all the constructors take 0 arguments in the class) so error CS1729 pops up 11 times.

What SnipeShare version are you using? - I've tried each of the forked versions but can't seem to find one that makes it work.

Or do you have any Windows build instructions?

**Comment by danielhogg** [comment]
You are correct, Marksman is using an updated version of the SnipeSharp API.

To build Marksman, you will need to use our version of the API [here](https://github.com/Scope-IT/SnipeSharp).
