### ISSUE TITLE
issue running agent

### ISSUE THREAD

**Issue by mdesnoyers** [Scope-IT/marksman#17]
When we run the agent, we get the following error....

C:\Program Files (x86)\Scope-IT\Marksman>marksman
5/15/2019 9:47:44 AM: Started application.
HTTP 200: Connection to Snipe-IT instance succeded.
Attempting to create type: SnipeSharp.Endpoints.Models.Manufacturer
Instance name: LENOVO
Already exists in DB
Attempting to create type: SnipeSharp.Endpoints.Models.Category
Instance name: Desktop
Already exists in DB
Attempting to create type: SnipeSharp.Endpoints.Models.Model
Instance name: 10MR0004US
Already exists in DB
Attempting to create type: SnipeSharp.Endpoints.Models.Company
Instance name: PACT

Unhandled Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at SnipeSharp.Endpoints.EndpointManager`1.FindOne(ISearchFilter filter)
   at SnipeSharp.Endpoints.EndpointManager`1.Create(T toCreate)
   at Marksman.Broker.SyncAll(SnipeItApi snipe, Asset currentAsset, Model currentModel, Manufacturer currentManufacturer, Category currentCategory, Company currentCompany, StatusLabel currentStatusLabel, Location currentLocation)
   at Marksman.Marksman.Main(String[] args)

**Comment by danielhogg** [comment]
Looks like it's having an issue with creating the company. What is the value of your company key in the appSettings block of your config file? It will look something like this:

```xml
<add key="Company" value="YOUR_COMPANY_HERE"/>
```

**Comment by mdesnoyers** [comment]
This is what we have

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
    </startup>
  <system.diagnostics>
    <trace autoflush="true" indentsize="4">
      <listeners>
        <add name="consoleListener" type="System.Diagnostics.ConsoleTraceListener"/>
        <remove name="Default" />
      </listeners>
    </trace>
  </system.diagnostics>
  <appSettings>
    <add key="API" value="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjRhYzVhYmI3MTM5OWI4YjUwYjQ1MGQ0NmY5ZDhlZGY0NWM4YTI5YmNlNWQ5NWE0NTBhZGI0MzQ5NjUyYzhlMWQwNWRlYmJmNmU5OGUwNTU5In0.eyJhdWQiOiIxIiwianRpIjoiNGFjNWFiYjcxMzk5YjhiNTBiNDUwZDQ2ZjlkOGVkZjQ1YzhhMjliY2U1ZDk1YTQ1MGFkYjQzNDk2NTJjOGUxZDA1ZGViYmY2ZTk4ZTA1NTkiLCJpYXQiOjE1NTc5Mjc5OTYsIm5iZiI6MTU1NzkyNzk5NiwiZXhwIjoxNTg5NTUwMzk2LCJzdWIiOiIxMDciLCJzY29wZXMiOltdfQ.y_9TcpNFktbYBPFzwzL00ohQoW5OeUfoUqbca68pjqFyDRQ6T5Ea1noE3cQ5fYOvl__50SxkseiLGCQQVvsdtmWUU8wUAyfT6c6evzYDi2SSme6pWUP1ILXhNT5gdVTNgfr0SkFRGbeK6VgVT7l6_LpVVgl_5m049VWJ8gk-RnJmSVuUmaPJC8-YfBM415gtvpoKgGpC3yZ5ykLVExbyvEsUcP_V2uTyXdkFeOIE3pN1Dto79eQSCIr2dHN0-3JLSYpj0Jr6aD3ACw7aZyoHWb1BGAeZuILAwUfcDqBFboI284XiIxmbxnLaqMvdD8j1u4FdLrvtTmiuPuBypOkEjkGHdq5akZbdX3cZ6qE7r44ZZbOJSCrx-B5bUWAOctNCWBR8PE8b8DvLdFxNkwf23BJWDiSUDtWcywd1SP8Yo_5xblZvczc3D7IZJCUVXU3iP3dzHbhBZVALVCLZVy8qAG88qk5Q1CePoA3uQ3Zc5wQCUISEjR8hf8m380RxQRtfiqhkFyNFNRdBamgbBiENkS-ugfS7WOcD2Zt6xrercjGEJnfJSzOUxBgWJcFxK36_PHSjvvWeO7WseySvRDwtxdJtEO0t_6pahq9rWBZus9AXzZWE4Zk68-SPMB1vljoTnD5E8neamearBkWwNaxfymtnRim97DKOGUtfng9DOec"/>
    <add key="BaseURI" value="http://inventory.pactmd.com/api/v1/"/>
    <add key="DefaultStatusLabel" value="In Production"/>
    <add key="Company" value="PACT"/>
    <add key="Location" value="MSO"/>
    <add key="OUEnabled" value="false"/>
    <add key="OULevel" value="1"/>
    <add key="Interactive" value="false"/>
    <add key="WarrantyMonths" value="60"/>
    <add key="AssetTagPrefix" value="001"/>
  </appSettings>

</configuration>

**Comment by mdesnoyers** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
    </startup>
  <system.diagnostics>
    <trace autoflush="true" indentsize="4">
      <listeners>
        <add name="consoleListener" type="System.Diagnostics.ConsoleTraceListener"/>
        <remove name="Default" />
      </listeners>
    </trace>
  </system.diagnostics>
  <appSettings>
    <add key="API" value="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjRhYzVhYmI3MTM5OWI4YjUwYjQ1MGQ0NmY5ZDhlZGY0NWM4YTI5YmNlNWQ5NWE0NTBhZGI0MzQ5NjUyYzhlMWQwNWRlYmJmNmU5OGUwNTU5In0.eyJhdWQiOiIxIiwianRpIjoiNGFjNWFiYjcxMzk5YjhiNTBiNDUwZDQ2ZjlkOGVkZjQ1YzhhMjliY2U1ZDk1YTQ1MGFkYjQzNDk2NTJjOGUxZDA1ZGViYmY2ZTk4ZTA1NTkiLCJpYXQiOjE1NTc5Mjc5OTYsIm5iZiI6MTU1NzkyNzk5NiwiZXhwIjoxNTg5NTUwMzk2LCJzdWIiOiIxMDciLCJzY29wZXMiOltdfQ.y_9TcpNFktbYBPFzwzL00ohQoW5OeUfoUqbca68pjqFyDRQ6T5Ea1noE3cQ5fYOvl__50SxkseiLGCQQVvsdtmWUU8wUAyfT6c6evzYDi2SSme6pWUP1ILXhNT5gdVTNgfr0SkFRGbeK6VgVT7l6_LpVVgl_5m049VWJ8gk-RnJmSVuUmaPJC8-YfBM415gtvpoKgGpC3yZ5ykLVExbyvEsUcP_V2uTyXdkFeOIE3pN1Dto79eQSCIr2dHN0-3JLSYpj0Jr6aD3ACw7aZyoHWb1BGAeZuILAwUfcDqBFboI284XiIxmbxnLaqMvdD8j1u4FdLrvtTmiuPuBypOkEjkGHdq5akZbdX3cZ6qE7r44ZZbOJSCrx-B5bUWAOctNCWBR8PE8b8DvLdFxNkwf23BJWDiSUDtWcywd1SP8Yo_5xblZvczc3D7IZJCUVXU3iP3dzHbhBZVALVCLZVy8qAG88qk5Q1CePoA3uQ3Zc5wQCUISEjR8hf8m380RxQRtfiqhkFyNFNRdBamgbBiENkS-ugfS7WOcD2Zt6xrercjGEJnfJSzOUxBgWJcFxK36_PHSjvvWeO7WseySvRDwtxdJtEO0t_6pahq9rWBZus9AXzZWE4Zk68-SPMB1vljoTnD5E8neamearBkWwNaxfymtnRim97DKOGUtfng9DOec"/>
    <add key="BaseURI" value="http://inventory.pactmd.com/api/v1/"/>
    <add key="DefaultStatusLabel" value="In Production"/>
    <add key="Company" value="PACT"/>
    <add key="Location" value="MSO"/>
    <add key="OUEnabled" value="false"/>
    <add key="OULevel" value="1"/>
    <add key="Interactive" value="false"/>
    <add key="WarrantyMonths" value="60"/>
    <add key="AssetTagPrefix" value="001"/>
  </appSettings>

</configuration>

**Comment by mdesnoyers** [comment]
<add key="BaseURI" value="YOUR ENDPOINT HERE (edited for security)"/>
    <add key="DefaultStatusLabel" value="In Production"/>
    <add key="Company" value="PACT"/>
    <add key="Location" value="MSO"/>
    <add key="OUEnabled" value="false"/>
    <add key="OULevel" value="1"/>
    <add key="Interactive" value="false"/>
    <add key="WarrantyMonths" value="60"/>
    <add key="AssetTagPrefix" value="001"/>
  </appSettings>

</configuration>

**Comment by mdesnoyers** [comment]
ok i set my value to "" and it work.... but we would like to be able to set per location or divisions

**Comment by danielhogg** [comment]
If you go to your SnipeIT frontend web interface, and go into Settings -> Companies, what entries are present currently?

**Comment by mdesnoyers** [comment]
![companies](https://user-images.githubusercontent.com/50491630/57787522-8adf2d80-7703-11e9-865f-20768742f0e4.JPG)
PACT
GCC
MCMA
PSS
CKC
WHMG
Ortho

**Comment by mdesnoyers** [comment]
it works for now, cant wait for future updates. thanks again for your help
