### ISSUE TITLE
Question: About the Agent

### ISSUE THREAD

**Issue by mdesnoyers** [Scope-IT/marksman#18]
Can you update existing assets information using the agent?

**Comment by danielhogg** [comment]
That is actually the next feature we are working on - automatic update functionality will be added in the next version release -> v1.5.0

**Comment by mdesnoyers** [comment]
great!!! what's the time frame on the release

**Comment by danielhogg** [comment]
We are targeting end of Q2, so the plan is to release before June 30th. You can be subscribed to notifications on releases by watching and starring the repository.
Cheers,
Daniel

**Comment by danielhogg** [comment]
Update functionality has been released in [version 1.5.0](https://github.com/Scope-IT/marksman/releases/tag/v1.5.0)
