### ISSUE TITLE
Is there a way to silently install Marksman with the marksman config settings preconfigured?

### ISSUE THREAD

**Issue by GoldBond007** [Scope-IT/marksman#21]
Is there a way to silently install Marksman with the marksman config settings preconfigured and then having it run the exe file automatically? 
I want to deploy Marksman on at least 200 laptops and installing the MSI manually is time consuming.

**Comment by danielhogg** [comment]
I wouldn't recommend doing it manually. One setup that we have found works well is to use a GPO (Group Policy Object), which allow you to do one-click deployment to all of the computers in your network. Here's the steps:

1. Put the marksman .exe in a network share
2. Deploy a GPO that has each laptop run a powershell script once on boot
3. Write a powershell script that will invoke Marksman.exe from the network share, and this can be done silently (see [this issue](https://github.com/Scope-IT/marksman/issues/10#issuecomment-468727703) for details).
