### ISSUE TITLE
When will the Component lookup (Hard drives, CPU, GPU,etc) feature be added to Marksman? Will it be able to tell us what software is loaded on a PC?

### ISSUE THREAD

**Issue by GoldBond007** [Scope-IT/marksman#22]
When will the Component lookup (Hard drives, CPU, GPU,etc) feature be added to Marksman? Will it be able to tell us what software is loaded on a PC?

**Comment by danielhogg** [comment]
An upcoming release (v1.5.0) is slated for June 30th, but it will not include component lookup. As this is an open-source project, we welcome any pull requests that implement the component lookup feature.

**Comment by hdrkhls** [comment]
so, now the agent still can't include with component lookup ?
i think that's will be great if the agent can do it

**Comment by hdrkhls** [comment]
@danielhogg 
do you have any suggestions for component lookup on asset from snipeit ?
