### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by 1TF0rward** [Scope-IT/marksman#23]
Hi,

I am trying to get this working but apparently the API is incorrect. I have regenerated one and tried that but no luck. Pleases can I get some help.

Also has there been any updates? I've seen that there should have been? I will find this extremely useful in my workplace.

**Comment by 1TF0rward** [comment]
I'm an idiot ignore me about the API!!! 

But other question is still relevant.

**Comment by danielhogg** [comment]
The update is completed and pushed to the [update-devel](https://github.com/Scope-IT/marksman/tree/update-devel) branch for marksman, and the [api-update](https://github.com/Scope-IT/SnipeSharp/tree/api_update) branch for our SnipeSharp API fork.

We are currently testing this version (1.5.0) in a variety of environments and will release a .msi installer at some point later this week.

Out of curiosity, what issue were you having with the API?

**Comment by 1TF0rward** [comment]
Hi,

Thank you! What is the SnipeSharp API? Is that something I need?

I was stupidly using the app key in the .env file of the install! Maybe ass a line that you can do this in the actual SnipeIT for dummies like me!
