### ISSUE TITLE
Solution Does Not Build

### ISSUE THREAD

**Issue by ghost** [Scope-IT/marksman#27]
Hi

I'm trying to compile Marksman from the repo however, I've encountered a few issues.
I have managed to successfully get the SnipeSharp solution built and it appears to be loading into the Marksman solution properly however, there appears to be issues within the Marksman solution preventing a successful build.

# Issues
Below are the issues I have encountered while trying to build this solution.

### MarksmanSetup (unavailable)
The marksman solution contains a VS installer (.vdproj) project however, this does not appear to be available either within this repository or another?

![image](https://user-images.githubusercontent.com/49189932/70043921-4476f080-15b9-11ea-96dd-2c458526c924.png)

### SearchFilter Errors
SearchFilter objects are created within `Broker.cs` however, the SearchFilter class does not contain a constructor that takes a single argument.

![image](https://user-images.githubusercontent.com/49189932/70043491-7e93c280-15b8-11ea-86be-e5cb9530562c.png)

### Full Error List
In addition to the two errors listed above, the errors in the below screenshot are also present when attempting to build the solution.

![image](https://user-images.githubusercontent.com/49189932/70044075-86a03200-15b9-11ea-8df8-dbdc65979667.png)

# Environment
OS: Windows 10
IDE: Visual Studio 2015 (Community Edition)

**Comment by danielhogg** [comment]
I think you're having the same issue that was present here: https://github.com/Scope-IT/marksman/issues/11

First, compile [SnipeSharp](https://github.com/Scope-IT/SnipeSharp) (our fork, not the original), as it is a dependency. Then, in the Marksman project you will need to add a reference to our version of SnipeSharp. After this, Marksman should compile correctly.

Let me know if that fixes your issue. I'm leaving this open for now, because I will need to create a section in the README that better explains this process.

**Comment by ghost** [comment]
Ah, the SnipeSharp build will be the issue then! I used the official repo and not the forked copy..

I'll compile the fork and then try compile Marksman again, I'll update after testing.

**Comment by ghost** [comment]
Confirmed - Build is successful after compiling forked SnipeSharp repo.

Could you provide any information about the MarksmanSetup project?
Is that available from somewhere or is that propriety?

**Comment by danielhogg** [comment]
The MarksmanSetup project is for generating the .msi files (Windows Installer Package) that we ship with [every major release](https://github.com/Scope-IT/marksman/releases). It is not necessary for the operation of Marksman.

**Comment by danielhogg** [comment]
987d7cedce4
Added developer guide section to README to explain build process.
