### ISSUE TITLE
Update functionality

### ISSUE THREAD

**Issue by danielhogg** [Scope-IT/marksman#6]
Work with the update functionality in SnipeSharp api

**Comment by CCUKAaron** [comment]
Would be nice if the agent updated existing attributes on each run. For example:-

`Attempting to create type: SnipeSharp.Endpoints.Models.Location`
`Instance name: Newcastle`
`Already exists in DB`

Does not make any change in the Snipe-It Web Interface unfortunately.

**Comment by CCUKAaron** [comment]
Need to give this a try, but not got console access to the host at this very moment...

https://snipe-it.readme.io/docs/asset-location-sync

**Comment by danielhogg** [comment]
The update functionality has been added in the latest release, [v1.5.0](https://github.com/Scope-IT/marksman/releases/tag/v1.5.0).
