### ISSUE TITLE
Latest build with manufacturer fixes

### ISSUE THREAD

**Issue by snipe** [Scope-IT/marksman#9]
Hi there! @snipe (of Snipe-IT) here! 

First off, thanks for writing this! It's a very cool project, and we're excited to see what you do with it! We were hoping you'd be willing to issue a new release with your manufacturer fixes in it, as we have a user who is trying to get Scope-IT working with Snipe-IT, and is hitting errors, specifically:

```
Unhandled Exception: SnipeSharp.Exceptions.RequiredValueIsNullException: Property Manufacturer cannot be null.
   at SnipeSharp.Endpoints.QueryParameterBuilder.GetParameters(Object item)
   at SnipeSharp.Common.RequestManagerRestSharp.Post(String path, ICommonEndpointModel item)
   at SnipeSharp.Endpoints.EndpointManager`1.Create(T toCreate)
   at Marksman.Sentry.GetAsset(NameValueCollection appSettings, SnipeItApi snipe)
   at Marksman.Marksman.Main(String[] args)
```

It looks like #5 might be the missing piece there, and we'd love it if he could download a version with that fix in it.

Thanks so much for your time, and for this awesome project!

**Comment by danielhogg** [comment]
Thanks for the positive feedback on the project!

We have released [v1.0.1](https://github.com/Scope-IT/marksman/releases/tag/v1.0.1) today, which includes an installer. This release fixes the manufacturer == null bug that a lot of our users were having.

I have tested v1.0.1 on our production instance of SnipeIT with ~250 assets, as well as on a fresh docker-based install of SnipeIT. I believe the issue is fixed - I would be really interested to hear if the new version works for your user.

**Comment by velaar** [comment]
@snipe 
Any chance we can ask you to include marksman in "Libraries, Modules & Related Projects" under Snipe-IT? We would really appreciate more testing and community help on this one

**Comment by snipe** [comment]
@velaar you got it

Closing this issue for now - thanks everyone!

**Comment by eddy445** [comment]
@danielhogg Hello, Ive just tried out the new v1.5.0 and I'm getting a similar error see screenshot bellow
![error marksman](https://user-images.githubusercontent.com/77179439/212304987-88260866-dca1-42ba-9829-a5b615e509f7.png)

**Comment by eddy445** [comment]
@danielhogg never mind the above error, the issue was with the API key's permission full multi-company is enabled in my instance and the key didn't have all the necessary permissions, once that was sorted the error went away.
